# Generated by Django 5.1 on 2024-08-18 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('image', models.URLField(null=True)),
                ('password', models.CharField(max_length=100)),
                ('seen', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'username'],
                'indexes': [models.Index(fields=['slug'], name='api_admin_slug_2fc7cc_idx'), models.Index(fields=['username'], name='api_admin_usernam_91a688_idx'), models.Index(fields=['last_name', 'first_name'], name='api_admin_last_na_d087ee_idx')],
            },
        ),
        migrations.CreateModel(
            name='Advisers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('image', models.URLField(null=True)),
                ('seen', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name', '-created_at'],
                'indexes': [models.Index(fields=['slug'], name='api_adviser_slug_1ce073_idx'), models.Index(fields=['last_name', 'first_name'], name='api_adviser_last_na_9fef6b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=50, null=True)),
                ('seen', models.PositiveBigIntegerField(default=0)),
                ('image', models.URLField(null=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'nickname'],
                'indexes': [models.Index(fields=['slug'], name='api_clients_slug_24c3d2_idx'), models.Index(fields=['nickname'], name='api_clients_nicknam_658237_idx'), models.Index(fields=['last_name', 'first_name'], name='api_clients_last_na_80bfcc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('logo', models.URLField(null=True)),
                ('seen', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title', '-created_at'],
                'indexes': [models.Index(fields=['slug'], name='api_feature_slug_e3d015_idx'), models.Index(fields=['title'], name='api_feature_title_06ed2b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.URLField(null=True)),
                ('seen', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title', '-created_at'],
                'indexes': [models.Index(fields=['slug'], name='api_offers_slug_2d9cab_idx'), models.Index(fields=['title'], name='api_offers_title_92c8f3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.URLField(null=True)),
                ('seen', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title', '-created_at'],
                'indexes': [models.Index(fields=['slug'], name='api_service_slug_78ef48_idx'), models.Index(fields=['title'], name='api_service_title_4949c7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clients')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.services')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.URLField(null=True)),
                ('seen', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.admin')),
            ],
            options={
                'ordering': ['title', '-created_at'],
                'indexes': [models.Index(fields=['slug'], name='api_blog_slug_c3801f_idx'), models.Index(fields=['title'], name='api_blog_title_33ec30_idx')],
            },
        ),
    ]
